# Generated by Django 4.1.7 on 2023-04-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_user_image_alter_lesson_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='avatar',
        ),
    ]
